### ISSUE TITLE
  Titanium 3.5.0 64bit support?

### ISSUE THREAD

**Issue by AppWerft** [pegli/TiCarousel#24]
I tried to recompile for 64-bit. But in the zip the vendor folder is empty. Now I have copied from iCarosuel. 
After building I got a runnable module. 
UPDATE:
But on run time  the behaviour is changed. I can trigger the animation only by swiping on "border" (outside) the visible view. Swiping on the main view doesn't  trigger the carousel.
The same issue with version from developer branch.

**Comment by caspahouzer** [comment]
:+1:

**Comment by andrzejschmidt** [comment]
Have the same problem here. Apart from that seems like wrapping of carousel items stopped working.

**Comment by yozef** [comment]
There is a pull request by @caspahouzer https://github.com/pegli/TiCarousel/pull/25 open

**Comment by pegli** [comment]
The 1.2 build up in the Releases section of the project has 64-bit support.
