### ISSUE TITLE
Where is module.zip file for both android and iphone platform in Repository?

### ISSUE THREAD

**Issue by hitesh-gondaliya** [pegli/TiCarousel#26]

**Comment by yozef** [comment]
Pretty sure this is an iOS Module only.

**Comment by hitesh-gondaliya** [comment]
Thanks for replay..
in ios module also missing module.zip file

**Comment by pegli** [comment]
I've created a release for the current version of the module here:

    https://github.com/pegli/TiCarousel/releases/tag/1.2

I recommend using [Gittio](http://gitt.io) to install and update modules in your Titanium projects.  The new release should be available through Gittio in about 24 hours.
