### ISSUE TITLE
'iCarousel.h' file not found

### ISSUE THREAD

**Issue by jamesdevries** [pegli/TiCarousel#7]
Experiencing this error when trying to compile the module:

TiCarousel/mobile/ios/Classes/ComObscureTiCarouselCarouselViewProxy.h:11:9: fatal error: 'iCarousel.h' file not found

**Comment by phamdatt** [comment]
> that fixed it. thanks!

how do you fixed it ? please support for me

**Comment by aybarska** [comment]
i still got this error
